---
language: node_js
node_js:
  - "stable"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
